trigger:
- master

jobs:
- job: RunTest
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: Login to dbaas
    inputs:
      command: login
      containerRegistry: dbaas
  - script: |
      docker run dbaas.docker.repositories.sap.ondemand.com/com.sap.hana.dbaas.delivery/haas-jenkins-lib:cli-stayup groovy -cp /root/scripts/src /root/scripts/src/haas/microdelivery/cli/Cli.groovy --command hello