# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
#container: ubuntu:18.04  
#steps:
#- script: printenv

container:
 image: dbaas.docker.repositories.sap.ondemand.com/com.sap.hana.dbaas.delivery/haas-jenkins-lib:cli-stayup
 endpoint: dbaas
steps:
- script: groovy -cp src ./src/haas/microdelivery/cli/Cli.groovy --command hello
#- script: echo hello